language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - npm install -g jshint
#  - gem install sass compass modular-scale
script:
  - "jshint ."
notifications:
  email:
    - ac@digitalsurgeons.com
