language: node_js
node_js:
- '0.10'
before_install:
- npm install -g jshint
script:
- jshint .
notifications:
  email:
    recipients:
      secure: UNJgPUfNuTgI0jTwwZ/rpt6kQWnxnN/7fESCA9h2fSdYjE0vej+hyfN4E0iRz7CKtkHZFskeCuYurSp8CAEl0kyCFCUI1QmAm4PwGkKVyvKjxO2e1SFk/kaoupLHh6jmUwcDbTTW1WCWT/dONRjLwOag2g4HswprUyY3AwgNLqk=
